/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;

import javax.swing.JOptionPane;
import com.mycompany.FileHandling.FileHandle;
import com.mycompany.adminFunc.AdminMainFunc;

/**
 *
 * @author Asus
 */
public class AdminPage extends javax.swing.JFrame {

    /**
     * Creates new form AdminPage
     */
    public AdminPage() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        hiBtn = new javax.swing.JButton();
        haBtn = new javax.swing.JButton();
        srBtn = new javax.swing.JButton();
        rptBtn = new javax.swing.JButton();
        LogOutBtn = new javax.swing.JButton();
        wlcLabel = new javax.swing.JLabel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        hiTable = new javax.swing.JTable();
        hiAddBtn = new javax.swing.JButton();
        hiUptBtn = new javax.swing.JButton();
        hiDelBtn = new javax.swing.JButton();
        rIDfield = new javax.swing.JTextField();
        rNameField = new javax.swing.JTextField();
        priceField = new javax.swing.JTextField();
        rIDLabel = new javax.swing.JLabel();
        rNameLabel = new javax.swing.JLabel();
        rTypeLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        desTextArea = new javax.swing.JTextArea();
        priceLabel = new javax.swing.JLabel();
        desLabel = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        ownerField = new javax.swing.JTextField();
        availLabel = new javax.swing.JLabel();
        availBox = new javax.swing.JComboBox<>();
        clrBtn = new javax.swing.JButton();
        rTypeField = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        haTable = new javax.swing.JTable();
        applEndBtn = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        stdRecordTable = new javax.swing.JTable();
        rIDFLbl = new javax.swing.JLabel();
        rTypeLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        stdNameField = new javax.swing.JTextField();
        stdRTypeField = new javax.swing.JTextField();
        stdDateField = new javax.swing.JTextField();
        duraLbl = new javax.swing.JLabel();
        stdDuraField = new javax.swing.JTextField();
        contLbl = new javax.swing.JLabel();
        stdContField = new javax.swing.JTextField();
        stdRIDField = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOSTEL ADMIN");
        setBackground(new java.awt.Color(0, 0, 0));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(242, 242, 242));
        jPanel2.setForeground(new java.awt.Color(51, 51, 51));

        hiBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        hiBtn.setText("Hostel Information");
        hiBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiBtnActionPerformed(evt);
            }
        });

        haBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        haBtn.setText("Hostel Application");
        haBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                haBtnActionPerformed(evt);
            }
        });

        srBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        srBtn.setText("Student Record");
        srBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                srBtnActionPerformed(evt);
            }
        });

        rptBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        rptBtn.setText("Report");
        rptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptBtnActionPerformed(evt);
            }
        });

        LogOutBtn.setBackground(new java.awt.Color(35, 134, 255));
        LogOutBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        LogOutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogOutBtn.setText("Log Out");
        LogOutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutBtnActionPerformed(evt);
            }
        });

        wlcLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        wlcLabel.setForeground(new java.awt.Color(0, 0, 0));
        wlcLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        wlcLabel.setText("Welcome back Admin!!\n");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wlcLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LogOutBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(srBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(haBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(hiBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(wlcLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hiBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(haBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(srBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rptBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jTabbedPane3.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane3.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane3.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane3.setToolTipText("");
        jTabbedPane3.setEnabled(false);
        jTabbedPane3.setOpaque(true);

        jPanel10.setBackground(new java.awt.Color(153, 153, 153));

        hiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Name", "Room Type", "Description", "Price (MYS)", "Availability", "Owner"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        hiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hiTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(hiTable);
        if (hiTable.getColumnModel().getColumnCount() > 0) {
            hiTable.getColumnModel().getColumn(0).setResizable(false);
            hiTable.getColumnModel().getColumn(1).setResizable(false);
            hiTable.getColumnModel().getColumn(2).setResizable(false);
            hiTable.getColumnModel().getColumn(3).setResizable(false);
            hiTable.getColumnModel().getColumn(4).setResizable(false);
            hiTable.getColumnModel().getColumn(5).setResizable(false);
            hiTable.getColumnModel().getColumn(6).setResizable(false);
        }

        hiAddBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        hiAddBtn.setText("ADD");
        hiAddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiAddBtnActionPerformed(evt);
            }
        });

        hiUptBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        hiUptBtn.setText("UPDATE");
        hiUptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiUptBtnActionPerformed(evt);
            }
        });

        hiDelBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        hiDelBtn.setText("DELETE");
        hiDelBtn.setToolTipText("");
        hiDelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hiDelBtnActionPerformed(evt);
            }
        });

        rIDLabel.setText("Room ID");

        rNameLabel.setText("Room Name");

        rTypeLabel.setText("Room Type");

        desTextArea.setColumns(20);
        desTextArea.setRows(5);
        jScrollPane4.setViewportView(desTextArea);

        priceLabel.setText("Price");

        desLabel.setText("Description");

        ownerLabel.setText("Owner");

        availLabel.setText("Availablility");

        availBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<--Availability-->", "Available", "Booked" }));
        availBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availBoxActionPerformed(evt);
            }
        });

        clrBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        clrBtn.setText("Clear");
        clrBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clrBtnActionPerformed(evt);
            }
        });

        rTypeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Room Type", "Small", "Medium", "Master" }));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(rIDLabel)
                                .addGap(36, 36, 36)
                                .addComponent(rIDfield))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rNameLabel)
                                    .addComponent(rTypeLabel)
                                    .addComponent(availLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(rNameField)
                                    .addComponent(availBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rTypeField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(desLabel)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(priceField, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                    .addComponent(ownerField))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hiDelBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hiUptBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hiAddBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clrBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rIDfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hiAddBtn)
                    .addComponent(rIDLabel)
                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceLabel))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rNameLabel)
                    .addComponent(hiUptBtn)
                    .addComponent(ownerLabel)
                    .addComponent(ownerField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(hiDelBtn)
                        .addGap(18, 18, 18)
                        .addComponent(clrBtn))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(desLabel)
                            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rTypeLabel)
                                .addComponent(rTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(availLabel)
                            .addComponent(availBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("HOSTEL", jPanel10);

        jPanel6.setBackground(new java.awt.Color(153, 153, 153));

        haTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Room ID", "Room Type", "Month", "Price (MYS)", "Username", "Name", "Start Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(haTable);
        if (haTable.getColumnModel().getColumnCount() > 0) {
            haTable.getColumnModel().getColumn(0).setResizable(false);
            haTable.getColumnModel().getColumn(1).setResizable(false);
            haTable.getColumnModel().getColumn(2).setResizable(false);
            haTable.getColumnModel().getColumn(3).setResizable(false);
            haTable.getColumnModel().getColumn(4).setResizable(false);
            haTable.getColumnModel().getColumn(5).setResizable(false);
            haTable.getColumnModel().getColumn(6).setResizable(false);
        }

        applEndBtn.setText("End");
        applEndBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applEndBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 755, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(applEndBtn)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(applEndBtn)
                .addGap(16, 16, 16))
        );

        jTabbedPane3.addTab("HOSTEL", jPanel6);

        jPanel8.setBackground(new java.awt.Color(153, 153, 153));
        jPanel8.setForeground(new java.awt.Color(0, 0, 0));

        stdRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Contact", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        stdRecordTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                stdRecordTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(stdRecordTable);
        if (stdRecordTable.getColumnModel().getColumnCount() > 0) {
            stdRecordTable.getColumnModel().getColumn(0).setResizable(false);
            stdRecordTable.getColumnModel().getColumn(1).setResizable(false);
            stdRecordTable.getColumnModel().getColumn(2).setResizable(false);
            stdRecordTable.getColumnModel().getColumn(3).setResizable(false);
        }

        rIDFLbl.setText("Room ID");

        rTypeLbl.setText("Room Type");

        dateLbl.setText("Date");

        nameLbl.setText("Name");

        duraLbl.setText("Duration");

        contLbl.setText("Contact");

        stdRIDField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rooms" }));
        stdRIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdRIDFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(contLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(stdContField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(rIDFLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(stdRIDField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(75, 75, 75)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rTypeLbl, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(nameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(stdRTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(duraLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stdDuraField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(stdNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(dateLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stdDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dateLbl)
                            .addComponent(stdDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stdNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameLbl)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rIDFLbl)
                            .addComponent(stdRIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stdDuraField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(duraLbl))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(stdRTypeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rTypeLbl)
                        .addComponent(contLbl))
                    .addComponent(stdContField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("HOSTEL", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane3)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(965, 680));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void hiBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiBtnActionPerformed
        jTabbedPane3.setSelectedIndex(0);
        AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
        amf.displyRoomData(hiTable);
    }//GEN-LAST:event_hiBtnActionPerformed

    private void haBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_haBtnActionPerformed
        jTabbedPane3.setSelectedIndex(1);
        AdminMainFunc amf = new AdminMainFunc(FileHandle.RESERVATION);
        amf.displyApplicData(haTable);
    }//GEN-LAST:event_haBtnActionPerformed

    private void srBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_srBtnActionPerformed
        jTabbedPane3.setSelectedIndex(2);
        AdminMainFunc amf = new AdminMainFunc(FileHandle.ACCOUNT);
        amf.displyStdRecData(stdRecordTable);
    }//GEN-LAST:event_srBtnActionPerformed

    private void rptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptBtnActionPerformed
        AdminGenerateReport rp = new AdminGenerateReport();
        rp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rptBtnActionPerformed

    private void LogOutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutBtnActionPerformed
        login lg = new login();
        lg.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LogOutBtnActionPerformed

    private void hiUptBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiUptBtnActionPerformed
        Validation v = new Validation();
        if(!rIDfield.isEnabled()){
            if(rIDfield.getText().isEmpty() || rNameField.getText().isEmpty() || rTypeField.getSelectedIndex() == 0 || desTextArea.getText().isEmpty() || priceField.getText().isEmpty() 
                || availBox.getSelectedIndex() == 0 || ownerField.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Please fill in the form!!","Error Message", JOptionPane.ERROR_MESSAGE);
            }else if(v.validatePrice(priceField.getText())==false){
                JOptionPane.showMessageDialog(this,"Please enter the price!!","Error Message", JOptionPane.ERROR_MESSAGE);
                priceField.setText("");
            }else{
                String roomID = rIDfield.getText();
                String roomName = rNameField.getText();
                String roomType = (String)rTypeField.getSelectedItem();
                String desc = desTextArea.getText();
                double price = Double.parseDouble(priceField.getText());
                String availability = (String) availBox.getSelectedItem();
                String owner = ownerField.getText();
                
                
                room r = new room(roomID,roomName,roomType,desc,price,availability.toLowerCase(),owner); 
                r.setRoomData(r);
                hostel roomData = r.getRoomData();
                FileHandle fh = new FileHandle(FileHandle.ROOM);
                int res = fh.UpdateRoomData(roomData);
                resetFunc();
                if(res == 1){
                    rIDfield.setEnabled(true);
                    JOptionPane.showMessageDialog(null, "Update Success");
                    AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
                    amf.displyRoomData(hiTable);
                    availBox.setEnabled(true);
                    ownerField.setEnabled(true);
                }else if(res == 2){
                    JOptionPane.showMessageDialog(null, "Invalid User!!! This USER is not exist in our system!!", "ERROR MESSAGE", JOptionPane.ERROR_MESSAGE);
                    rIDfield.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this,"This Room is not exist Please add before edit!!","Error Message", JOptionPane.ERROR_MESSAGE);
                }


            }
        }else{
            JOptionPane.showMessageDialog(this, "Please Select a Room!!");
        }
        
        
    }//GEN-LAST:event_hiUptBtnActionPerformed

    private void hiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hiTableMouseClicked
        AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
        amf.onClickRoomRecordTbl(hiTable, rIDfield, rTypeField, rNameField, desTextArea, priceField, availBox, ownerField);
        
    }//GEN-LAST:event_hiTableMouseClicked

    private void hiAddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiAddBtnActionPerformed
        Validation v= new Validation();
        if(rIDfield.getText().isEmpty() || rNameField.getText().isEmpty() || rTypeField.getSelectedIndex() == 0 || desTextArea.getText().isEmpty() || priceField.getText().isEmpty() 
                || availBox.getSelectedIndex() == 0 || ownerField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Please fill in the form!!","Error Message", JOptionPane.ERROR_MESSAGE);
        }else if(v.validatePrice(priceField.getText())==false){
            JOptionPane.showMessageDialog(this,"Please enter the price!!","Error Message", JOptionPane.ERROR_MESSAGE);
            priceField.setText("");
        }else if(v.validateRoomID(rIDfield.getText().toUpperCase())==false){
            JOptionPane.showMessageDialog(this,"ROOM ID only accept IDs start with S, M, MS!!!","Error Message", JOptionPane.ERROR_MESSAGE);
            rIDfield.setText("");
        }else if(availBox.getSelectedIndex() == 2){
            JOptionPane.showMessageDialog(this,"You are only able to add an available room!!!","Error Message", JOptionPane.ERROR_MESSAGE);

        }else{
       
            if(!rIDfield.isEnabled()){
                JOptionPane.showMessageDialog(this, "Please Clear the Form before you add a new Data!");
            }else{
                String roomID = rIDfield.getText().toUpperCase();
                String roomName = rNameField.getText();
                String roomType = (String)rTypeField.getSelectedItem();
                String desc = desTextArea.getText();
                double price = Double.parseDouble(priceField.getText());
                String availability = (String) availBox.getSelectedItem();
                String owner = ownerField.getText();

                room r = new room(roomID,roomName,roomType,desc,price,availability.toLowerCase(),owner);
                r.setRoomData(r);
                hostel roomData = r.getRoomData();
                FileHandle fh = new FileHandle(FileHandle.ROOM);
                int res = fh.AddRoomData(roomData);
                if(res == 1){
                    
                    JOptionPane.showMessageDialog(null, "Add Success!!");
                    resetFunc();
                    AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
                    amf.displyRoomData(hiTable); 
                    ownerField.setEnabled(true);
                    
                }else if(res == -1){
                    JOptionPane.showMessageDialog(this, "This User is invalid!! Please insert a valid User!!","Errror Message", JOptionPane.ERROR_MESSAGE);
                    ownerField.setText("");
                    ownerField.setEnabled(true);
                }else{
                    JOptionPane.showMessageDialog(this, "This Room ID is USED!! Please insert a new Room ID!!","Errror Message", JOptionPane.ERROR_MESSAGE);
                    rIDfield.setText("");
                }
            }
           
        }
    }//GEN-LAST:event_hiAddBtnActionPerformed
    
    private void clrBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clrBtnActionPerformed
        rIDfield.setEnabled(true);
        availBox.setEnabled(true);
        ownerField.setEnabled(true);
        resetFunc();

    }//GEN-LAST:event_clrBtnActionPerformed

    private void hiDelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hiDelBtnActionPerformed
        
        int respone =  JOptionPane.showConfirmDialog(this , "Are you sure you want to end this application ?", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);

         if(respone == JOptionPane.YES_OPTION){
            if(!rIDfield.isEnabled()){
                room r = new room(rIDfield.getText(),rNameField.getText(),(String)rTypeField.getSelectedItem(),
                        desTextArea.getText(),Double.parseDouble(priceField.getText()), (String) availBox.getSelectedItem(),ownerField.getText());
                r.setRoomData(r);
                hostel roomData = r.getRoomData();
                FileHandle fh = new FileHandle(FileHandle.ROOM);
                fh.DeleteRoomData(roomData);
                resetFunc();
                rIDfield.setEnabled(true);
                rTypeField.setEnabled(true);
                JOptionPane.showMessageDialog(null, "Delete Success");
                AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
                amf.displyRoomData(hiTable);
            }else{
                JOptionPane.showMessageDialog(this, "Please Select a Room!!");
                
            }
         }else{
             JOptionPane.showMessageDialog(this, "Process cancel!!"); 
             resetFunc();
         }
        
    }//GEN-LAST:event_hiDelBtnActionPerformed

    private void availBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availBoxActionPerformed
        if(availBox.getSelectedIndex() == 1){
            ownerField.setText("null");
            ownerField.setEnabled(false); 
        }else{
            ownerField.setText("");
            ownerField.setEnabled(true); 
        }
    }//GEN-LAST:event_availBoxActionPerformed

    private void applEndBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applEndBtnActionPerformed
        int respone =  JOptionPane.showConfirmDialog(this , "Are you sure you want to delete this application ?", "Confirm", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(respone == JOptionPane.YES_OPTION){
            AdminMainFunc amf = new AdminMainFunc(FileHandle.ROOM);
            amf.endApplication(haTable);
            
        }else{
            JOptionPane.showMessageDialog(this, "Process cancel!!"); 
        }
        AdminMainFunc amf =  new AdminMainFunc(FileHandle.RESERVATION);
        amf.displyApplicData(haTable); 
    }//GEN-LAST:event_applEndBtnActionPerformed

    private void stdRecordTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stdRecordTableMouseClicked
        AdminMainFunc amf = new AdminMainFunc(FileHandle.RESERVATION);
        amf.onClickStdRecoTable(stdRecordTable, stdNameField, stdContField, stdRIDField, stdRTypeField, stdDateField, stdDuraField);
    }//GEN-LAST:event_stdRecordTableMouseClicked

    private void stdRIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdRIDFieldActionPerformed
        AdminMainFunc amf = new AdminMainFunc(FileHandle.RESERVATION);
        amf.onClickRoomID(stdRIDField, stdRTypeField, stdDateField, stdDuraField);

    }//GEN-LAST:event_stdRIDFieldActionPerformed

    public void resetFunc(){
        rIDfield.setText("");
        rNameField.setText("");
        rTypeField.setSelectedIndex(0);
        desTextArea.setText("");
        ownerField.setText("");
        priceField.setText("");
        availBox.setSelectedIndex(0);
    }
    

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogOutBtn;
    private javax.swing.JButton applEndBtn;
    private javax.swing.JComboBox<String> availBox;
    private javax.swing.JLabel availLabel;
    private javax.swing.JButton clrBtn;
    private javax.swing.JLabel contLbl;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel desLabel;
    private javax.swing.JTextArea desTextArea;
    private javax.swing.JLabel duraLbl;
    private javax.swing.JButton haBtn;
    private javax.swing.JTable haTable;
    private javax.swing.JButton hiAddBtn;
    private javax.swing.JButton hiBtn;
    private javax.swing.JButton hiDelBtn;
    private javax.swing.JTable hiTable;
    private javax.swing.JButton hiUptBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JTextField ownerField;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel rIDFLbl;
    private javax.swing.JLabel rIDLabel;
    private javax.swing.JTextField rIDfield;
    private javax.swing.JTextField rNameField;
    private javax.swing.JLabel rNameLabel;
    private javax.swing.JComboBox<String> rTypeField;
    private javax.swing.JLabel rTypeLabel;
    private javax.swing.JLabel rTypeLbl;
    private javax.swing.JButton rptBtn;
    private javax.swing.JButton srBtn;
    private javax.swing.JTextField stdContField;
    private javax.swing.JTextField stdDateField;
    private javax.swing.JTextField stdDuraField;
    private javax.swing.JTextField stdNameField;
    private javax.swing.JComboBox<String> stdRIDField;
    private javax.swing.JTextField stdRTypeField;
    private javax.swing.JTable stdRecordTable;
    private javax.swing.JLabel wlcLabel;
    // End of variables declaration//GEN-END:variables
}
