/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Tan Zhong
 */
public class Payment extends javax.swing.JFrame {

    public static String roomID_Selected;
    public static String roomType_Selected;
    public static String fee;
    public static String length_renting;
    public static String username;
    
    /**
     * Creates new form Payment
     */
    public Payment(String roomID_Selected, String roomType_Selected, String fee, String length_renting, String userName) {
        initComponents();
        Payment.roomID_Selected = roomID_Selected;
        Payment.roomType_Selected = roomType_Selected;
        Payment.fee = fee;
        Payment.length_renting = length_renting;
        Payment.username = userName;
        userLab2.setText(username);
        displayFee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentLab1 = new javax.swing.JLabel();
        PaymentLab2 = new javax.swing.JLabel();
        paymentNameLab = new javax.swing.JLabel();
        paymentCNLab = new javax.swing.JLabel();
        paymentEDLab = new javax.swing.JLabel();
        paymentCVVLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        paymentTotalLab1 = new javax.swing.JLabel();
        paymentTotalLab2 = new javax.swing.JLabel();
        paymentConfirmBtn = new javax.swing.JButton();
        paymentNameTxt = new javax.swing.JTextField();
        paymentCVVtxt = new javax.swing.JPasswordField();
        paymentCNTxt = new javax.swing.JTextField();
        paymentEDTxt = new javax.swing.JTextField();
        userLab1 = new javax.swing.JLabel();
        userLab2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        paymentLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentLab1.setText("Payment");

        PaymentLab2.setText("Please fill in your card's details to proceed payment");

        paymentNameLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameLab.setText("Name:");

        paymentCNLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNLab.setText("Card Number:");

        paymentEDLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDLab.setText("Expiry Date:");

        paymentCVVLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCVVLab.setText("CVV:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paymentTotalLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab1.setText("Total: RM");

        paymentTotalLab2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab2.setText("1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(paymentTotalLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTotalLab1)
                    .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        paymentConfirmBtn.setText("Confirm");
        paymentConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentConfirmBtnActionPerformed(evt);
            }
        });

        paymentNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentNameTxt.setText("Student Name");
        paymentNameTxt.setToolTipText("Thomas Tan");
        paymentNameTxt.setActionCommand("<Not Set>");
        paymentNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentNameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentNameTxtFocusLost(evt);
            }
        });

        paymentCVVtxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentCVVtxt.setText("123");
        paymentCVVtxt.setToolTipText("123");
        paymentCVVtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentCVVtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentCVVtxtFocusLost(evt);
            }
        });

        paymentCNTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentCNTxt.setText("xxxx-xxxx-xxxx-xxxx");
        paymentCNTxt.setToolTipText("xxxx-xxxx-xxxx-xxxx");
        paymentCNTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentCNTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentCNTxtFocusLost(evt);
            }
        });

        paymentEDTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentEDTxt.setText("01/24");
        paymentEDTxt.setToolTipText("mm/YY");
        paymentEDTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentEDTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentEDTxtFocusLost(evt);
            }
        });

        userLab1.setText("User:");

        userLab2.setText("User001");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaymentLab2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentCVVLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentEDLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentNameLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentCNLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(paymentCVVtxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(backBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentConfirmBtn))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(userLab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(paymentLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLab2)
                    .addComponent(userLab1))
                .addGap(3, 3, 3)
                .addComponent(paymentLab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentLab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentNameLab)
                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCNLab)
                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentEDLab)
                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCVVLab)
                    .addComponent(paymentCVVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentConfirmBtn)
                    .addComponent(backBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displayFee(){
        paymentTotalLab2.setText(fee);
    }
    
    //Validation for name of cardholder
    private boolean validateName(String name){
        //Name cannot be empty
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this, "Cardholder name is required!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        //Name can only contains alphabets
        if(!name.matches("[a-zA-Z ]+")){
            JOptionPane.showMessageDialog(this, "Cardholder name only allows alphabets!", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
    
    //Validation for card
    private boolean validateCard(String cardNo, String expiryDate, String cvv){
        //The accepted format of card number is xxxx-xxxx-xxxx-xxxx
        if (!cardNo.matches("\\d{4}-\\d{4}-\\d{4}-\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Invalid card number.\nPlease follow this format xxxx-xxxx-xxxx-xxxx.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //The accepted format of date is MM/yy
        if (!expiryDate.matches("\\d{2}/\\d{2}")) {
            JOptionPane.showMessageDialog(this, "Invalid expiry date. Please follow this format mm/YY.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        //The accepted format of cvv is 3 digits
        if (!cvv.matches("\\d{3}")) {
            JOptionPane.showMessageDialog(this, "Invalid cvv. CVV is 3 digits.", "Error", JOptionPane.ERROR_MESSAGE);
            return false;
        }

        return true;
    }
    
    //When the payment button is clicked,
    //It will check all the inputs
    private void paymentConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentConfirmBtnActionPerformed
        // TODO add your handling code here:
        String cardHolder = paymentNameTxt.getText();
        String cardNo = paymentCNTxt.getText();
        String expiryDate = paymentEDTxt.getText();
        String cvv = paymentCVVtxt.getText();
        
        boolean valid_name = validateName(cardHolder);
        boolean valid_card = validateCard(cardNo, expiryDate, cvv);
        
        if(valid_name && valid_card){
            int response = JOptionPane.showConfirmDialog
                (this, "Are you sure you want to proceed to payment?", 
                "Confirm!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION)
            {
                Receipt r = new Receipt(username, roomID_Selected, roomType_Selected, length_renting, fee);
                r.setVisible(true);
                this.dispose();
            }
        }
    }//GEN-LAST:event_paymentConfirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        RoomReservation rr = new RoomReservation(username, roomID_Selected);
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    //Remove placeholder
    private void paymentNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentNameTxtFocusGained
        // TODO add your handling code here:
        if(paymentNameTxt.getText().equals("Student Name")){
            paymentNameTxt.setText("");
            paymentNameTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentNameTxtFocusGained

    //Display placeholder
    private void paymentNameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentNameTxtFocusLost
        // TODO add your handling code here:
        if(paymentNameTxt.getText().isEmpty()){
            paymentNameTxt.setText("Student Name");
            paymentNameTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentNameTxtFocusLost

    //Remove placeholder
    private void paymentCNTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCNTxtFocusGained
        // TODO add your handling code here:
        if(paymentCNTxt.getText().equals("xxxx-xxxx-xxxx-xxxx")){
            paymentCNTxt.setText("");
            paymentCNTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentCNTxtFocusGained

    //Display placeholder
    private void paymentCNTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCNTxtFocusLost
        // TODO add your handling code here:
        if(paymentCNTxt.getText().isEmpty()){
            paymentCNTxt.setText("xxxx-xxxx-xxxx-xxxx");
            paymentCNTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentCNTxtFocusLost

    //Remove placeholder
    private void paymentEDTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentEDTxtFocusGained
        // TODO add your handling code here:
        if(paymentEDTxt.getText().equals("01/24")){
            paymentEDTxt.setText("");
            paymentEDTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentEDTxtFocusGained

    //Display placeholder
    private void paymentEDTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentEDTxtFocusLost
        // TODO add your handling code here:
        if(paymentEDTxt.getText().isEmpty()){
            paymentEDTxt.setText("01/24");
            paymentEDTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentEDTxtFocusLost

    //Remove placeholder
    private void paymentCVVtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCVVtxtFocusGained
        // TODO add your handling code here:
        if(paymentCVVtxt.getText().equals("123")){
            paymentCVVtxt.setText("");
            paymentCVVtxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentCVVtxtFocusGained

    //Display placeholder
    private void paymentCVVtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCVVtxtFocusLost
        // TODO add your handling code here:
        if(paymentCVVtxt.getText().isEmpty()){
            paymentCVVtxt.setText("123");
            paymentCVVtxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentCVVtxtFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment(roomID_Selected, roomType_Selected, fee, length_renting, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaymentLab2;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel paymentCNLab;
    private javax.swing.JTextField paymentCNTxt;
    private javax.swing.JLabel paymentCVVLab;
    private javax.swing.JPasswordField paymentCVVtxt;
    private javax.swing.JButton paymentConfirmBtn;
    private javax.swing.JLabel paymentEDLab;
    private javax.swing.JTextField paymentEDTxt;
    private javax.swing.JLabel paymentLab1;
    private javax.swing.JLabel paymentNameLab;
    private javax.swing.JTextField paymentNameTxt;
    private javax.swing.JLabel paymentTotalLab1;
    private javax.swing.JLabel paymentTotalLab2;
    private javax.swing.JLabel userLab1;
    private javax.swing.JLabel userLab2;
    // End of variables declaration//GEN-END:variables
}
