/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;

import java.awt.Color;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Tan Zhong
 */
public class Payment extends javax.swing.JFrame {

    public static String roomID_Selected;
    public static String roomType_Selected;
    public static String fee;
    public static String length_renting;
    public static String username;
    
    /**
     * Creates new form Payment
     */
    public Payment(String roomID_Selected, String roomType_Selected, String fee, String length_renting, String userName) {
        initComponents();
        Payment.roomID_Selected = roomID_Selected;
        Payment.roomType_Selected = roomType_Selected;
        Payment.fee = fee;
        Payment.length_renting = length_renting;
        Payment.username = userName;
        userLab2.setText(username);
        displayFee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        paymentCNTxt = new javax.swing.JTextField();
        paymentConfirmBtn = new javax.swing.JButton();
        paymentNameTxt = new javax.swing.JTextField();
        paymentLab1 = new javax.swing.JLabel();
        paymentCVVtxt = new javax.swing.JPasswordField();
        PaymentLab2 = new javax.swing.JLabel();
        paymentEDTxt = new javax.swing.JTextField();
        paymentNameLab = new javax.swing.JLabel();
        userLab1 = new javax.swing.JLabel();
        paymentCNLab = new javax.swing.JLabel();
        userLab2 = new javax.swing.JLabel();
        paymentEDLab = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        paymentCVVLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        paymentTotalLab1 = new javax.swing.JLabel();
        paymentTotalLab2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        paymentCNTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentCNTxt.setText("xxxx-xxxx-xxxx-xxxx");
        paymentCNTxt.setToolTipText("xxxx-xxxx-xxxx-xxxx");
        paymentCNTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentCNTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentCNTxtFocusLost(evt);
            }
        });
        paymentCNTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentCNTxtKeyPressed(evt);
            }
        });

        paymentConfirmBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        paymentConfirmBtn.setText("Confirm");
        paymentConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentConfirmBtnActionPerformed(evt);
            }
        });

        paymentNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentNameTxt.setText("Student Name");
        paymentNameTxt.setToolTipText("Thomas Tan");
        paymentNameTxt.setActionCommand("<Not Set>");
        paymentNameTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentNameTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentNameTxtFocusLost(evt);
            }
        });
        paymentNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentNameTxtKeyPressed(evt);
            }
        });

        paymentLab1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        paymentLab1.setText("Payment");

        paymentCVVtxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentCVVtxt.setText("***");
        paymentCVVtxt.setToolTipText("123");
        paymentCVVtxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentCVVtxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentCVVtxtFocusLost(evt);
            }
        });
        paymentCVVtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentCVVtxtKeyPressed(evt);
            }
        });

        PaymentLab2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        PaymentLab2.setText("Please fill in your card's details to proceed payment");

        paymentEDTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDTxt.setForeground(new java.awt.Color(204, 204, 204));
        paymentEDTxt.setText("MM/yy");
        paymentEDTxt.setToolTipText("MM/yy");
        paymentEDTxt.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                paymentEDTxtFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                paymentEDTxtFocusLost(evt);
            }
        });
        paymentEDTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                paymentEDTxtKeyPressed(evt);
            }
        });

        paymentNameLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameLab.setText("Name:");

        userLab1.setText("User:");

        paymentCNLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNLab.setText("Card Number:");

        userLab2.setText("User001");

        paymentEDLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDLab.setText("Expiry Date:");

        backBtn.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        paymentCVVLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCVVLab.setText("CVV:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paymentTotalLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab1.setText("Total: RM");

        paymentTotalLab2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab2.setText("1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(paymentTotalLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTotalLab1)
                    .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaymentLab2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(backBtn)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentConfirmBtn))
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentCVVLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentEDLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentNameLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentCNLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentCVVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(userLab1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(userLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(paymentLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(userLab2)
                    .addComponent(userLab1))
                .addGap(3, 3, 3)
                .addComponent(paymentLab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentLab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentNameLab)
                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCNLab)
                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentEDLab)
                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCVVLab)
                    .addComponent(paymentCVVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentConfirmBtn)
                    .addComponent(backBtn))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void displayFee(){
        paymentTotalLab2.setText(fee);
    }
    
    //When the payment button is clicked,
    //It will check all the inputs
    private void paymentConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentConfirmBtnActionPerformed
        // TODO add your handling code here:
        String cardHolder = paymentNameTxt.getText();
        String cardNo = paymentCNTxt.getText();
        String expiryDate = paymentEDTxt.getText();
        String cvv = paymentCVVtxt.getText();
        
        Student student = new Student(username);
        boolean paid = student.makePayment(cardHolder,cardNo,expiryDate,cvv);
        if(paid){
            
            int response = JOptionPane.showConfirmDialog
                (this, "Congratulation! The room "+roomID_Selected+" is reserved by you.\nDo you need a receipt for this room reservation?", 
                "Confirm!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
            if(response == JOptionPane.YES_OPTION)
            {
                Receipt r = new Receipt(username, roomID_Selected, roomType_Selected, length_renting, fee);
                r.setVisible(true);
                this.dispose();
            }else{
                Receipt r = new Receipt(username, roomID_Selected, roomType_Selected, length_renting, fee);
                StudentPanel sp = new StudentPanel(username);
                sp.setVisible(true);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_paymentConfirmBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        RoomReservation rr = new RoomReservation(username, roomID_Selected);
        rr.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    //Remove placeholder
    private void paymentNameTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentNameTxtFocusGained
        // TODO add your handling code here:
        if(paymentNameTxt.getText().equals("Student Name")){
            paymentNameTxt.setText("");
            paymentNameTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentNameTxtFocusGained

    //Display placeholder
    private void paymentNameTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentNameTxtFocusLost
        // TODO add your handling code here:
        if(paymentNameTxt.getText().isEmpty()){
            paymentNameTxt.setText("Student Name");
            paymentNameTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentNameTxtFocusLost

    //Remove placeholder
    private void paymentCNTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCNTxtFocusGained
        // TODO add your handling code here:
        if(paymentCNTxt.getText().equals("xxxx-xxxx-xxxx-xxxx")){
            paymentCNTxt.setText("");
            paymentCNTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentCNTxtFocusGained

    //Display placeholder
    private void paymentCNTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCNTxtFocusLost
        // TODO add your handling code here:
        if(paymentCNTxt.getText().isEmpty()){
            paymentCNTxt.setText("xxxx-xxxx-xxxx-xxxx");
            paymentCNTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentCNTxtFocusLost

    //Remove placeholder
    private void paymentEDTxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentEDTxtFocusGained
        // TODO add your handling code here:
        if(paymentEDTxt.getText().equals("MM/yy")){
            paymentEDTxt.setText("");
            paymentEDTxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentEDTxtFocusGained

    //Display placeholder
    private void paymentEDTxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentEDTxtFocusLost
        // TODO add your handling code here:
        if(paymentEDTxt.getText().isEmpty() || paymentEDTxt.getText().equals("MM/yy")){
            paymentEDTxt.setText("MM/yy");
            paymentEDTxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentEDTxtFocusLost

    //Remove placeholder
    private void paymentCVVtxtFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCVVtxtFocusGained
        // TODO add your handling code here:
        if(paymentCVVtxt.getText().equals("***")){
            paymentCVVtxt.setText("");
            paymentCVVtxt.setForeground(Color.black);
        }
    }//GEN-LAST:event_paymentCVVtxtFocusGained

    //Display placeholder
    private void paymentCVVtxtFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_paymentCVVtxtFocusLost
        // TODO add your handling code here:
        if(paymentCVVtxt.getText().isEmpty() || paymentCVVtxt.getText().equals("***")){
            paymentCVVtxt.setText("***");
            paymentCVVtxt.setForeground(Color.lightGray);
        }
    }//GEN-LAST:event_paymentCVVtxtFocusLost

    //Auto fill in hypen after 4 digits
    private void paymentCNTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentCNTxtKeyPressed
        // TODO add your handling code here
        String value=paymentCNTxt.getText();
        if(value.length()== 4 || value.length()== 9 || value.length()== 14){
            paymentCNTxt.setText(value+"-"); 
        }

        if(evt.getKeyCode() == KeyEvent.VK_ENTER || value.length()== 18) {
            paymentEDTxt.requestFocus(); 
        }
           
    }//GEN-LAST:event_paymentCNTxtKeyPressed

    //Press enter and jump to next input field
    private void paymentNameTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentNameTxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            paymentCNTxt.requestFocus();
        }
    }//GEN-LAST:event_paymentNameTxtKeyPressed

    //Auto fill in slash after 2 digits
    private void paymentEDTxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentEDTxtKeyPressed
        // TODO add your handling code here:
        String value=paymentEDTxt.getText();
        if(value.length()== 2){
            paymentEDTxt.setText(value+"/"); 
        }
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER || value.length()== 4) {
            paymentCVVtxt.requestFocus(); 
        }
    }//GEN-LAST:event_paymentEDTxtKeyPressed
    
    //Press enter and confirm payment
    private void paymentCVVtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_paymentCVVtxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER) {
            String cardHolder = paymentNameTxt.getText();
            String cardNo = paymentCNTxt.getText();
            String expiryDate = paymentEDTxt.getText();
            String cvv = paymentCVVtxt.getText();

            Student student = new Student(username);
            boolean paid = student.makePayment(cardHolder,cardNo,expiryDate,cvv);
            if(paid){

                int response = JOptionPane.showConfirmDialog
                    (this, "Congratulation! The room "+roomID_Selected+" is reserved by you.\nDo you need a receipt for this room reservation?", 
                    "Confirm!",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                if(response == JOptionPane.YES_OPTION)
                {
                    Receipt r = new Receipt(username, roomID_Selected, roomType_Selected, length_renting, fee);
                    r.setVisible(true);
                    this.dispose();
                }else{
                    Receipt r = new Receipt(username, roomID_Selected, roomType_Selected, length_renting, fee);
                    StudentPanel sp = new StudentPanel(username);
                    sp.setVisible(true);
                    this.dispose();
                }

            }
        }
    }//GEN-LAST:event_paymentCVVtxtKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment(roomID_Selected, roomType_Selected, fee, length_renting, username).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaymentLab2;
    private javax.swing.JButton backBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paymentCNLab;
    private javax.swing.JTextField paymentCNTxt;
    private javax.swing.JLabel paymentCVVLab;
    private javax.swing.JPasswordField paymentCVVtxt;
    private javax.swing.JButton paymentConfirmBtn;
    private javax.swing.JLabel paymentEDLab;
    private javax.swing.JTextField paymentEDTxt;
    private javax.swing.JLabel paymentLab1;
    private javax.swing.JLabel paymentNameLab;
    private javax.swing.JTextField paymentNameTxt;
    private javax.swing.JLabel paymentTotalLab1;
    private javax.swing.JLabel paymentTotalLab2;
    private javax.swing.JLabel userLab1;
    private javax.swing.JLabel userLab2;
    // End of variables declaration//GEN-END:variables
}
