/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;

/**
 *
 * @author Tan Zhong
 */
public class Payment extends javax.swing.JFrame {

    /**
     * Creates new form Payment
     */
    public Payment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentLab1 = new javax.swing.JLabel();
        PaymentLab2 = new javax.swing.JLabel();
        paymentNameLab = new javax.swing.JLabel();
        paymentCNLab = new javax.swing.JLabel();
        paymentEDLab = new javax.swing.JLabel();
        paymentCVVLab = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        paymentTotalLab1 = new javax.swing.JLabel();
        paymentTotalLab2 = new javax.swing.JLabel();
        paymentConfirmBtn = new javax.swing.JButton();
        paymentNameTxt = new javax.swing.JTextField();
        paymentCVVtxt = new javax.swing.JPasswordField();
        paymentCNTxt = new javax.swing.JTextField();
        paymentEDTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Payment");

        paymentLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentLab1.setText("Payment");

        PaymentLab2.setText("Please fill in your card's details to proceed payment");

        paymentNameLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameLab.setText("Name:");

        paymentCNLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNLab.setText("Card Number:");

        paymentEDLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDLab.setText("Expiry Date:");

        paymentCVVLab.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCVVLab.setText("CVV:");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        paymentTotalLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab1.setText("Total: RM");

        paymentTotalLab2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        paymentTotalLab2.setText("1000");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(paymentTotalLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentTotalLab1)
                    .addComponent(paymentTotalLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        paymentConfirmBtn.setText("Confirm");
        paymentConfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentConfirmBtnActionPerformed(evt);
            }
        });

        paymentNameTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentNameTxt.setText("Student Name");
        paymentNameTxt.setToolTipText("Thomas Tan");

        paymentCVVtxt.setText("123");
        paymentCVVtxt.setToolTipText("123");

        paymentCNTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentCNTxt.setText("xxxx-xxxx-xxxx-xxxx");
        paymentCNTxt.setToolTipText("xxxx-xxxx-xxxx-xxxx");

        paymentEDTxt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymentEDTxt.setText("01/24");
        paymentEDTxt.setToolTipText("mm/YY");
        paymentEDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentEDTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PaymentLab2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentCVVLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentEDLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentNameLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(paymentCNLab, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                    .addComponent(paymentCVVtxt)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(paymentConfirmBtn)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(paymentLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(paymentLab1)
                .addGap(8, 8, 8)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PaymentLab2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentNameLab)
                    .addComponent(paymentNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCNLab)
                    .addComponent(paymentCNTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentEDLab)
                    .addComponent(paymentEDTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(paymentCVVLab)
                    .addComponent(paymentCVVtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paymentConfirmBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void paymentConfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentConfirmBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentConfirmBtnActionPerformed

    private void paymentEDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentEDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymentEDTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Payment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Payment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PaymentLab2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel paymentCNLab;
    private javax.swing.JTextField paymentCNTxt;
    private javax.swing.JLabel paymentCVVLab;
    private javax.swing.JPasswordField paymentCVVtxt;
    private javax.swing.JButton paymentConfirmBtn;
    private javax.swing.JLabel paymentEDLab;
    private javax.swing.JTextField paymentEDTxt;
    private javax.swing.JLabel paymentLab1;
    private javax.swing.JLabel paymentNameLab;
    private javax.swing.JTextField paymentNameTxt;
    private javax.swing.JLabel paymentTotalLab1;
    private javax.swing.JLabel paymentTotalLab2;
    // End of variables declaration//GEN-END:variables
}
