/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;

/**
 *
 * @author Tan Zhong
 */
public class Receipt extends javax.swing.JFrame {

    /**
     * Creates new form Receipt
     */
    public Receipt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        receiptLab1 = new javax.swing.JLabel();
        receiptLab2 = new javax.swing.JLabel();
        receiptPanel = new javax.swing.JPanel();
        receiptNameLab1 = new javax.swing.JLabel();
        receiptDOBLab1 = new javax.swing.JLabel();
        receiptEmailLab1 = new javax.swing.JLabel();
        receiptMobileLab1 = new javax.swing.JLabel();
        receiptRoomIDLab1 = new javax.swing.JLabel();
        receiptTypeLab1 = new javax.swing.JLabel();
        receiptPeriodLab1 = new javax.swing.JLabel();
        receiptPriceLab1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        receiptNameLab2 = new javax.swing.JLabel();
        receiptDOBLab2 = new javax.swing.JLabel();
        receiptEmailLab2 = new javax.swing.JLabel();
        receiptMobileLab2 = new javax.swing.JLabel();
        receiptRoomIDLab2 = new javax.swing.JLabel();
        receiptTypeLab2 = new javax.swing.JLabel();
        receiptPeriodLab2 = new javax.swing.JLabel();
        receiptPriceLab2 = new javax.swing.JLabel();
        receiptOKBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        receiptLab1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        receiptLab1.setText("The Room is successfully reversed by you");

        receiptLab2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        receiptLab2.setText("Please kindly check the information below. Thank you.");

        receiptPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        receiptNameLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptNameLab1.setText("Student Name:");

        receiptDOBLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptDOBLab1.setText("Date of Birth: ");

        receiptEmailLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptEmailLab1.setText("Email:");

        receiptMobileLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptMobileLab1.setText("Mobile:");

        receiptRoomIDLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptRoomIDLab1.setText("Room ID:");

        receiptTypeLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptTypeLab1.setText("Type");

        receiptPeriodLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptPeriodLab1.setText("Period:");

        receiptPriceLab1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptPriceLab1.setText("Monthly Rental:");

        receiptNameLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptNameLab2.setText("Name");

        receiptDOBLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptDOBLab2.setText("DOB");

        receiptEmailLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptEmailLab2.setText("Email");

        receiptMobileLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptMobileLab2.setText("Mobile Number");

        receiptRoomIDLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptRoomIDLab2.setText("MR0101");

        receiptTypeLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptTypeLab2.setText("Master Room");

        receiptPeriodLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptPeriodLab2.setText("6 Months");

        receiptPriceLab2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        receiptPriceLab2.setText("RM1000");

        javax.swing.GroupLayout receiptPanelLayout = new javax.swing.GroupLayout(receiptPanel);
        receiptPanel.setLayout(receiptPanelLayout);
        receiptPanelLayout.setHorizontalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receiptNameLab1, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(receiptDOBLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptEmailLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptMobileLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptRoomIDLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptTypeLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptPeriodLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptPriceLab1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(receiptNameLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptDOBLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptEmailLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptMobileLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptRoomIDLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptTypeLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(receiptPeriodLab2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addComponent(receiptPriceLab2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(60, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );
        receiptPanelLayout.setVerticalGroup(
            receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(receiptPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptNameLab1)
                    .addComponent(receiptNameLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptDOBLab1)
                    .addComponent(receiptDOBLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptEmailLab1)
                    .addComponent(receiptEmailLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptMobileLab1)
                    .addComponent(receiptMobileLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptRoomIDLab1)
                    .addComponent(receiptRoomIDLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptTypeLab1)
                    .addComponent(receiptTypeLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptPeriodLab1)
                    .addComponent(receiptPeriodLab2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(receiptPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(receiptPriceLab1)
                    .addComponent(receiptPriceLab2))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        receiptOKBtn.setText("OK");
        receiptOKBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                receiptOKBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(receiptLab1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(receiptOKBtn)
                        .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(receiptLab2, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(receiptLab1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(receiptLab2)
                .addGap(18, 18, 18)
                .addComponent(receiptPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(receiptOKBtn)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void receiptOKBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_receiptOKBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_receiptOKBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel receiptDOBLab1;
    private javax.swing.JLabel receiptDOBLab2;
    private javax.swing.JLabel receiptEmailLab1;
    private javax.swing.JLabel receiptEmailLab2;
    private javax.swing.JLabel receiptLab1;
    private javax.swing.JLabel receiptLab2;
    private javax.swing.JLabel receiptMobileLab1;
    private javax.swing.JLabel receiptMobileLab2;
    private javax.swing.JLabel receiptNameLab1;
    private javax.swing.JLabel receiptNameLab2;
    private javax.swing.JButton receiptOKBtn;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JLabel receiptPeriodLab1;
    private javax.swing.JLabel receiptPeriodLab2;
    private javax.swing.JLabel receiptPriceLab1;
    private javax.swing.JLabel receiptPriceLab2;
    private javax.swing.JLabel receiptRoomIDLab1;
    private javax.swing.JLabel receiptRoomIDLab2;
    private javax.swing.JLabel receiptTypeLab1;
    private javax.swing.JLabel receiptTypeLab2;
    // End of variables declaration//GEN-END:variables
}
