/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.hostelmanagement;
import javax.swing.*;
import java.awt.*;
import java.awt.font.TextAttribute;
import java.util.Date;
import java.util.Map;
/**
 *
 * @author Asus
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        UsernameField = new javax.swing.JTextField();
        Usernamelabel = new javax.swing.JLabel();
        Emaillabel = new javax.swing.JLabel();
        EmailField = new javax.swing.JTextField();
        PassLabel = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        signupBtn = new javax.swing.JButton();
        loginTxt = new javax.swing.JTextField();
        DOBlabel = new javax.swing.JLabel();
        DOBField = new javax.swing.JTextField();
        Namelabel = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        ContactField = new javax.swing.JTextField();
        Contactlabel = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(43, 43, 43));
        jLabel1.setText("Sign In");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hostel");

        jPanel1.setBackground(new java.awt.Color(242, 242, 242));
        jPanel1.setPreferredSize(new java.awt.Dimension(298, 438));

        jLabel2.setBackground(new java.awt.Color(102, 102, 102));
        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(43, 43, 43));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Registration");

        UsernameField.setBackground(new java.awt.Color(233, 233, 233));
        UsernameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        UsernameField.setCaretColor(new java.awt.Color(0, 0, 0));
        UsernameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        UsernameField.setMargin(new java.awt.Insets(2, 7, 2, 6));
        UsernameField.setOpaque(true);

        Usernamelabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Usernamelabel.setForeground(new java.awt.Color(184, 184, 184));
        Usernamelabel.setText("Username");
        Usernamelabel.setEnabled(false);

        Emaillabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Emaillabel.setForeground(new java.awt.Color(184, 184, 184));
        Emaillabel.setText("Email");
        Emaillabel.setEnabled(false);

        EmailField.setBackground(new java.awt.Color(233, 233, 233));
        EmailField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        EmailField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        EmailField.setCaretColor(new java.awt.Color(0, 0, 0));
        EmailField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        EmailField.setMargin(new java.awt.Insets(2, 7, 2, 6));
        EmailField.setOpaque(true);

        PassLabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        PassLabel.setText("Password");
        PassLabel.setEnabled(false);

        jPasswordField1.setBackground(new java.awt.Color(233, 233, 233));
        jPasswordField1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        jPasswordField1.setCaretColor(new java.awt.Color(0, 0, 0));
        jPasswordField1.setOpaque(true);
        jPasswordField1.setPreferredSize(new java.awt.Dimension(1, 16));

        signupBtn.setBackground(new java.awt.Color(35, 134, 255));
        signupBtn.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        signupBtn.setForeground(new java.awt.Color(255, 255, 255));
        signupBtn.setText("Sign up");
        signupBtn.setBorder(null);
        signupBtn.setFocusPainted(false);
        signupBtn.setFocusable(false);
        signupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBtnActionPerformed(evt);
            }
        });

        loginTxt.setEditable(false);
        loginTxt.setBackground(new java.awt.Color(242, 242, 242));
        loginTxt.setFont(new java.awt.Font("Segoe UI Semilight", 0, 11)); // NOI18N
        loginTxt.setForeground(new java.awt.Color(0, 0, 0));
        loginTxt.setText("Already have an account? ");
        loginTxt.setBorder(null);
        loginTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                loginTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                loginTxtMouseExited(evt);
            }
        });

        DOBlabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        DOBlabel.setForeground(new java.awt.Color(184, 184, 184));
        DOBlabel.setText("Date of Birth");
        DOBlabel.setEnabled(false);

        DOBField.setBackground(new java.awt.Color(233, 233, 233));
        DOBField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        DOBField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        DOBField.setCaretColor(new java.awt.Color(0, 0, 0));
        DOBField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        DOBField.setMargin(new java.awt.Insets(2, 7, 2, 6));
        DOBField.setOpaque(true);

        Namelabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Namelabel.setForeground(new java.awt.Color(184, 184, 184));
        Namelabel.setText("Name");
        Namelabel.setEnabled(false);

        NameField.setBackground(new java.awt.Color(233, 233, 233));
        NameField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        NameField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        NameField.setCaretColor(new java.awt.Color(0, 0, 0));
        NameField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        NameField.setMargin(new java.awt.Insets(2, 7, 2, 6));
        NameField.setOpaque(true);

        ContactField.setBackground(new java.awt.Color(233, 233, 233));
        ContactField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        ContactField.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        ContactField.setCaretColor(new java.awt.Color(0, 0, 0));
        ContactField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        ContactField.setMargin(new java.awt.Insets(2, 7, 2, 6));
        ContactField.setOpaque(true);

        Contactlabel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 13)); // NOI18N
        Contactlabel.setForeground(new java.awt.Color(184, 184, 184));
        Contactlabel.setText("Contact");
        Contactlabel.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Contactlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContactField))
                    .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(PassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Emaillabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EmailField, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Usernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(UsernameField))
                    .addComponent(signupBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(DOBlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DOBField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Namelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NameField)))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Usernamelabel)
                    .addComponent(UsernameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Emaillabel)
                    .addComponent(EmailField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Namelabel)
                    .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DOBlabel)
                    .addComponent(DOBField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Contactlabel)
                    .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PassLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(signupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(loginTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBtnActionPerformed
        String uname = UsernameField.getText();
        String email = EmailField.getText();
        String pwd = jPasswordField1.getText();
        Date dob = new Date(1234567890000L);
        String name = NameField.getText();
        String contact = ContactField.getText();
        Student st = new Student(uname,pwd,name,dob,contact,email);
    }//GEN-LAST:event_signupBtnActionPerformed

    private void loginTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseClicked
        login lg = new login();
        lg.setVisible(true);
    }//GEN-LAST:event_loginTxtMouseClicked

    private void loginTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseEntered
        Font f = loginTxt.getFont();
        Map style = f.getAttributes();
        style.put(TextAttribute.UNDERLINE,TextAttribute.UNDERLINE_ON);
        loginTxt.setFont(f.deriveFont(style));
    }//GEN-LAST:event_loginTxtMouseEntered

    private void loginTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginTxtMouseExited
        Font f = loginTxt.getFont();
        Map style = f.getAttributes();
        style.put(TextAttribute.UNDERLINE,-1);
        loginTxt.setFont(f.deriveFont(style));
    }//GEN-LAST:event_loginTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            } 
          
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ContactField;
    private javax.swing.JLabel Contactlabel;
    private javax.swing.JTextField DOBField;
    private javax.swing.JLabel DOBlabel;
    private javax.swing.JTextField EmailField;
    private javax.swing.JLabel Emaillabel;
    private javax.swing.JTextField NameField;
    private javax.swing.JLabel Namelabel;
    private javax.swing.JLabel PassLabel;
    private javax.swing.JTextField UsernameField;
    private javax.swing.JLabel Usernamelabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField loginTxt;
    private javax.swing.JButton signupBtn;
    // End of variables declaration//GEN-END:variables
}
